### ISSUE TITLE
Deterministic

### ISSUE THREAD

**Issue by mrvollger** [ablab/TandemTools#2]
Hi,

I was wondering if TandemQUAST is deterministic.

Thanks!
Mitchell

**Comment by almiheenko** [comment]
Hi Mitchell,

TandemQUAST was almost fully deterministic except of the procedure of selecting a subset of k-mers in the regions where k-mer density is very high. However, now it should be fixed with the last commit.

**Comment by mrvollger** [comment]
HI,

Thanks for the answer, and the update. 

I had reran something and was getting different results and just wanted to make sure it was not on my end. 

Thanks!
Mitchell
